name: ItemReforge
version: '${project.version}'
main: ir.itemreforge.ItemReforge
api-version: 1.13
authors: [ ImRama ]
description: Reforge your items with random enchantments
depend:
  - Vault
commands:
  reforge:
